language: python
python: 3.3
env:
  - TOX_ENV=pypy
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py32
  - TOX_ENV=py27
  - TOX_ENV=py26
install:
  - pip install coveralls tox
script: tox -e  $TOX_ENV
after_success: coveralls
